project_id = "gshkmqvbhfzksgmuvout"

[api]
enabled = true
port = 54321
schemas = [
  "public",
  "graphql_public",
  "nba_game_lines",
  "graphql",
  "vault",
  "pgsodium_masks",
  "realtime",
  "pgsodium",
  "storage",
]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "https://gshkmqvbhfzksgmuvout.supabase.co"
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
secure_password_change = false
max_frequency = "1m0s"
otp_length = 6
otp_expiry = 3600

[functions]
[functions.odds-collector]
verify_jwt = false

[functions.odds-scheduler]
verify_jwt = false
