name: ai-sports-model-builder
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  # Data Science
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  # Jupyter
  - jupyter
  - ipykernel
  # API
  - requests
  # Development
  - black
  - flake8
  - pytest
  # Additional packages
  - pip:
    - schedule
    - python-dotenv
