from setuptools import setup, find_packages

setup(
    name="ai-sports-model",
    version="0.1.0",
    packages=find_packages(),
    include_package_data=True,
    python_requires=">=3.10",
    install_requires=[
        "sqlalchemy>=2.0.0",
        "psycopg2-binary>=2.9.9",
        "python-dotenv>=1.0.0",
        "alembic>=1.12.0",
        "pandas>=2.1.4",
        "numpy>=1.26.2",
        "scipy>=1.11.0",
        "requests>=2.31.0",
        "aiohttp>=3.9.1",
        "fastapi>=0.104.0",
        "uvicorn>=0.24.0",
    ],
    extras_require={
        "dev": [
            "black>=23.11.0",
            "isort>=5.12.0",
            "flake8>=6.1.0",
            "mypy>=1.7.0",
            "pytest>=7.4.0",
            "pytest-cov>=4.1.0",
            "pytest-mock>=3.12.0",
            "pytest-asyncio>=0.21.1",
            "pytest-xdist>=3.3.1",
            "pytest-sugar>=0.9.7",
            "pytest-timeout>=2.1.0",
        ],
        "ml": [
            "scikit-learn>=1.3.0",
            "tensorflow>=2.14.0",
            "pytorch>=2.1.0",
            "xgboost>=2.0.0",
            "lightgbm>=4.1.0",
        ],
        "docs": [
            "sphinx>=7.1.0",
            "sphinx-rtd-theme>=1.3.0",
        ],
    },
    entry_points={
        "console_scripts": [
            "sports-model=src.cli:main",
        ],
    },
    author="Your Name",
    author_email="your.email@example.com",
    description="AI Sports Model Builder for NBA, NFL, and NHL predictions",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    keywords="sports, betting, machine learning, AI, predictions",
    url="https://github.com/yourusername/ai-sports-model-builder",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.10",
    ],
)
