"""Add game table

Revision ID: 37505bd5f6d2
Revises: 001
Create Date: 2024-12-28 23:16:51.970891

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "37505bd5f6d2"
down_revision: Union[str, None] = "001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "game",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.String(length=100), nullable=False),
        sa.Column("season", sa.String(length=10), nullable=False),
        sa.Column("season_year", sa.Integer(), nullable=False),
        sa.Column("game_date", sa.DateTime(), nullable=False),
        sa.Column("game_day", sa.String(length=10), nullable=False),
        sa.Column("game_month", sa.Integer(), nullable=False),
        sa.Column("game_year", sa.Integer(), nullable=False),
        sa.Column("day_of_week", sa.String(length=10), nullable=False),
        sa.Column("start_time", sa.String(length=5), nullable=False),
        sa.Column("visitor_team_name", sa.String(length=100), nullable=False),
        sa.Column("home_team_name", sa.String(length=100), nullable=False),
        sa.Column("visitor_points", sa.Integer(), nullable=False),
        sa.Column("home_points", sa.Integer(), nullable=False),
        sa.Column("total_score", sa.Integer(), nullable=False),
        sa.Column("score_difference", sa.Integer(), nullable=False),
        sa.Column("home_win", sa.Boolean(), nullable=False),
        sa.Column("overtime", sa.Boolean(), nullable=False),
        sa.Column("ot_periods", sa.Integer(), nullable=False),
        sa.Column("attendance", sa.Integer(), nullable=True),
        sa.Column("arena", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("game_id"),
        schema="nba_game_lines",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("game", schema="nba_game_lines")
    # ### end Alembic commands ###
